name: Daily Open PR Check

on:
  schedule:
    # Schedule to run at 1 PM UTC, which is 10 PM KST.
    - cron: '0 13 * * *'

jobs:
  check_open_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          npm install @octokit/rest
      
      - name: Check for open PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          const { Octokit } = require("@octokit/rest");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          
          async function checkOpenPRs() {
            const { data } = await octokit.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            if (data.length > 0) {
              const message = `There are currently ${data.length} open pull requests.`;
              const curl = `curl -X POST -H 'Content-type: application/json' --data '{"text":"${message}"}' ${process.env.SLACK_WEBHOOK_URL}`;
              require('child_process').exec(curl, (error, stdout, stderr) => {
                if (error) {
                  console.error(`exec error: ${error}`);
                  return;
                }
                console.log(`stdout: ${stdout}`);
                console.log(`stderr: ${stderr}`);
              });
            }
          }

          checkOpenPRs();
