name: Release on Branch Deletion

on:
  delete:
    branches:
      - release/*

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract
        run: |
          BRANCH_REF=${GITHUB_REF##*/}
          echo "branch_name=$BRANCH_REF" >> $GITHUB_ENV

      - name: Create tag
        run: |
          TAG_NAME=${{ env.branch_name }}
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: actions/github-script@v6
        with:
          script: |
            const tag = process.env.branch_name;
            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              body: '',
              draft: false,
              prerelease: false,
              generate_release_notes: true
            });
            core.setOutput('release_url', response.data.html_url);
