name: Release on Branch Deletion

on:
  delete:
    branches:
      - release/*

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Extract branch name
        id: extract
        run: |
          BRANCH_REF=${{ github.event.ref }}
          VERSION_TAG=${BRANCH_REF#release/}
          echo "Clean up for branch $BRANCH_REF"
          echo "Extracted version: $VERSION_TAG"
          echo "branch_name=$VERSION_TAG" >> $GITHUB_ENV
